# The name of the package.
name: easy_event_calendar

# A brief description of the package.
description: "A simple event calendar for Flutter. Just pass events and this widget will show them in a calendar."

# The current version of the package.
version: 0.0.2+1

# The homepage URL for the package.
homepage: https://github.com/abdullah-bd/easy_event_calendar.git

environment:
  # The Dart SDK version required for this package.
  sdk: ^3.5.3

  # The Flutter SDK version required for this package.
  flutter: ">=1.17.0"

dependencies:
  # The Flutter framework as a dependency.
  flutter:
    sdk: flutter

  # The 'get' package for state management.
  get: ^4.6.6

  # The 'intl' package for internationalization and localization.
  intl: ^0.19.0

dev_dependencies:
  # The Flutter testing framework.
  flutter_test:
    sdk: flutter

  # The Flutter lints package for linting rules.
  flutter_lints: ^4.0.0


# Additional Flutter-specific configurations can be added here.